# version: '3.8'

services:
  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: syncdata-minio
      MINIO_ROOT_PASSWORD: syncdata-minio

  syncdata:
    build: . 
    ports:
      - "8080:8080"
    volumes:
      - .:/syncdata
    restart: on-failure
    depends_on:
      - minio
    environment:
      AWS_ENDPOINT: http://minio:9000
      AWS_ACCESS_KEY_ID: syncdata-minio
      AWS_SECRET_ACCESS_KEY: syncdata-minio